version: "3.8"

services:
  engine:
    image: netgrif-nae:4.2.0
    ports:
    - 8080:8080
    depends_on:
      - docker-mysql

  docker-mysql:
    image: mysql:5.7
    healthcheck:
      test: "/usr/bin/mysql -u root -psecret -e \"show databases;\""
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: nae
      MYSQL_USER: netgrif_nae
      MYSQL_PASSWORD: netgrif_nae
